apiVersion: v1
kind: Service
metadata:
  name: airbnb-serving
  labels:
    app: airbnb-serving
spec:
  type: ClusterIP
  selector:
    app: airbnb-serving
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
